apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: test-namespace
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: 500Mi
#          memory: 100Mi
          cpu: 0.1

