apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-dep-basic
  labels:
    app: rolling-dep-basic
spec:
  replicas: 6
  template:
    metadata:
      name: rolling-dep-basic
      labels:
        app: rolling-dep-basic
    spec:
      containers:
        - name: nginx
          image: nginx:1.5-err
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: rolling-dep-basic
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 0
#      maxUnavailable: 1
  minReadySeconds: 5
  revisionHistoryLimit: 10
