apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["echo"]
      args: ["The value of EMP_NAME env variable is: $(EMP_NAME)"]
      env:
      - name: EMP_NAME
        value: "Deiveehan"
  restartPolicy: Never
