apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolling-dep-basic
  labels:
    app: rolling-dep-basic
spec:
  replicas: 3
  template:
    metadata:
      name: rolling-dep-basic
      labels:
        app: rolling-dep-basic
    spec:
      containers:
        - name: rolling-dep-basic
          image: nginx:1.7.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: rolling-dep-basic
