apiVersion: v1
kind: Pod
metadata:
  name: label-pod-annotations
  labels:
    app: label-pod-basic
  annotations:
    editor: deivee
    location: Toronto
spec:
  containers:
    - name: label-pod-annotations
      image: busybox
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
