apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secretpod1
  name: secretpod1
spec:
  containers:
    - image: nginx
      name: secretpod1
      command: ['sh', '-c', "env"]
      resources: {}
      envFrom:
        - secretRef:
            name: testsecret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
