apiVersion: v1
kind: Pod
metadata:
  name: secretpod2
  labels:
    name: secret-test
spec:
  containers:
    - name: ssh-test-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
  volumes:
    - name: secret-volume
      secret:
        secretName: ssh-key-secret
