apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      command: ["echo"]
      args: ["$(EMP_NAME)"]
      env:
      - name: EMP_NAME
        value: "Deiveehan"
