apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronjobhello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cronjobhello
              image: busybox
              args:
                - /bin/sh
                - -c
                - date; echo Hello from Samson
          restartPolicy: OnFailure
