apiVersion: v1
kind: Pod
metadata:
  name: test-volume
spec:
  containers:
    - image: alpine
      name: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo 'hi' >> /opt/test.out;"]
      volumeMounts:
        - mountPath: /opt
          name: test-volume
  volumes:
    - name: test-volume
      hostPath:
        path: /data
        type: Directory

