apiVersion: v1
kind: Pod
metadata:
  name: pers-vol-pod-test
  labels:
    app: pers-vol-pod-test
spec:
  containers:
  - name: pers-vol-pod-test
    image: busybox
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: my-storage
      mountPath: "/tmp/storage"
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc

