apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: db-secret-volume
          mountPath: "/etc/db-secret"
          readOnly: true
  volumes:
    - name: db-secret-volume
      secret:
        secretName: db-secret
