apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: NAME_OF_PLAYER
        valueFrom:
          configMapKeyRef:
            key: player_name
            name: sportsmap
