apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /etc/sportsmap
          name: sportsmapvolume
  volumes:
    - name: sportsmapvolume
      configMap:
        name: sportsmap
