apiVersion: v1
kind: Pod
metadata:
  name: readiness-pod-basic
spec:
  containers:
  - name: testapp-container
    image: busybox
    command: ['sh', '-c', "echo Hello && sleep 3600"]
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
